Beginner.Blog/Controllers/ArticleController.cs
using Beginner.Blog.Core;
using Beginner.Blog.Models;
using Beginner.Blog.Service.Interfaces;
using Beginner.Blog.Service.Messaging.Request;
using Beginner.Blog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Beginner.Blog.Controllers
{
    public class ArticleController : BaseController
    {

        private readonly IRepository<Article> _articleRepository;
        private readonly IRepository<Category> _categoryRepository;
        private readonly IArticleService _articleService;
        public ArticleController(IRepository<Article> articleRepository, IRepository<Category> categoryRepository,
            IArticleService articleService)
        {
            _articleRepository = articleRepository;
            _categoryRepository = categoryRepository;
            _articleService = articleService;
        }
        public ActionResult List(int pageIndex = 1, int pageSize = 15)
        {
            //var query = _articleRepository.Table;

            var request = new GetPageArticlesRequest(pageIndex, pageSize);
            #region Filter
            var title = Request["title"];
            var category = Request["category"];
            var state = Request["state"];
            int cId;
            int s;

            if (!string.IsNullOrEmpty(title))
            {
                request.Title = title;
                ViewBag.ArticleTitle = title;
            }
            if (int.TryParse(category, out cId) && cId != 0)
            {
                request.CategoryId = cId;
                ViewBag.CagegotyId = cId;
            }
            if (int.TryParse(state, out s) && s != 0)
            {
                request.Status = s;
                ViewBag.State = s;
            }

            //排序
            var field = Request["field"];
            var sort = Request["sort"];

            var createTimeSort = "desc";

            if (field != null && sort != null)
            {
                if (field == "CreateTime" && (sort == "asc" || sort == "desc"))
                {
                    request.Sort = new Sort("CreateTime", sort == "asc" ? SortMode.Asc : SortMode.Desc);
                    createTimeSort = sort == "asc" ? "desc" : "asc";
                }
            }
            ViewBag.CreateTimeSort = createTimeSort;
            #endregion

            var response = _articleService.GetPageArticles(request);

            ViewBag.Categories = _categoryRepository.FindAll();

            return View(response.Pages);
        }
        public ActionResult Create()
        {
            ViewBag.Categories = _categoryRepository.FindAll();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ArticleModel model)
        {
            var article = new Article
            {
                Title = model.Title,
                Content = model.Content,
                Author = model.Author,
                CreateTime = DateTime.Now,
                IsTop = model.IsTop,
                State = model.State,
                Hits = model.Hits,
                Tags = model.Tags,
                CategoryId = model.CategoryId,
                Sort = model.Sort,
                MetaTitle = model.MetaTitle,
                MetaKeywords = model.MetaKeywords,
                MetaDescription = model.MetaDescription
            };

            _articleService.Insert(article);

            return RedirectToAction("List");
        }
        public ActionResult Edit(string articleId)
        {
            int id;
            if (int.TryParse(articleId, out id))
            {
                var article = _articleRepository.FindById(id);
                ViewBag.Categories = _categoryRepository.FindAll();
                if (article != null)
                    return View(article);
            }
            return RedirectToAction("NotFound", "Message");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ArticleModel model)
        {
            var article = _articleRepository.FindById(model.Id);

            article.Title = model.Title;
            article.Content = model.Content;
            article.Author = model.Author;
            article.IsTop = model.IsTop;
            article.State = model.State;
            article.Hits = model.Hits;
            article.Tags = model.Tags;
            article.CategoryId = model.CategoryId;
            article.Sort = model.Sort;
            article.MetaTitle = model.MetaTitle;
            article.MetaKeywords = model.MetaKeywords;
            article.MetaDescription = model.MetaDescription;

            _articleRepository.Update(article);

            return RedirectToAction("List");
        }
    }
}

Beginner.Blog/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Beginner.Blog.Controllers
{
    public class LogController : BaseController
    {
        // GET: Log
        public ActionResult List()
        {
            return View();
        }
    }
}

Beginner.Blog/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="keywords" content="@ViewBag.Keywords" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="author" content="@ViewBag.Author" />
    <title>@ViewBag.Title - 博客</title>
    <link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body class="blog-body">
    <div class="layui-header blog-header">
        <div class="blog-container">
            <div class="blog-header-title">
                <p><a href="/" style="color:#ffffff;">初学者</a></p>
            </div>
            <div class="blog-header-menu">
                <div class="blog-header-menu-icon">
                    <i class="layui-icon">&#xe60f;</i>
                </div>
                <ul class="layui-nav layui-nav-tree blog-header-menu-nav">
                    <li class="layui-nav-item"><a href="@Url.Action("List","Home")">首页</a></li>
                    @*<li class="layui-nav-item"><a href="@Url.Action("Archive", "Home")">文章归档</a></li>*@
                    <li class="layui-nav-item"><a href="@Url.Action("About","Home")">关于我</a></li>
                </ul>
            </div>
            <ul class="layui-nav blog-header-nav">
                <li class="layui-nav-item"><a href="@Url.Action("List","Home")">首页</a></li>
                @*<li class="layui-nav-item"><a href="@Url.Action("Archive", "Home")">文章归档</a></li>*@
                <li class="layui-nav-item"><a href="@Url.Action("About","Home")">关于我</a></li>
            </ul>
        </div>
    </div>
    <div class="layui-main blog-container">
        @RenderBody()
    </div>
    <div class="layui-footer">
        <div class="blog-footer-main">
            <p>Beginner © www.zhengjinfan.cn</p>
        </div>
    </div>
    <script src="~/Plugins/layui/layui.js"></script>
    <script>

        layui.use(['util','jquery'], function () {
            var util = layui.util,$ = layui.jquery;

            util.fixbar();

            $('.blog-header-menu-icon').on('click', function () {
                var $nav = $('.blog-header-menu-nav');
                $nav.toggle();
            });
        });


    </script>
    @RenderSection("scripts", false)
</body>
</html>

Beginner.Blog/Views/Shared/_ManageLayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - 后台管理</title>
    <link href="~/Plugins/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Plugins/layui/css/layui.css" rel="stylesheet" />
    <link href="~/Content/global.css" rel="stylesheet" />
</head>
<body class="layui-body-admin">
    <div class="layui-layout-admin">
        <div class="layui-header">
            <a href="#" class="logo layui-left"><img src="" alt="">初学者</a>
        </div>
        <div class="layui-side" style="background-color:#393D49; color:white;">
            <div style="height: 100px;padding: 5px;line-height: 40px;text-align: center;">
                <p>欢迎您，主人</p>
                <a href="@Url.Action("SignOut","Account")" style="border-radius:8px;" class="layui-btn layui-btn-small">退出</a>
            </div>
            <ul class="layui-nav layui-nav-tree">
                <li class="layui-nav-item layui-nav-title item-show" nav-item-num="4">
                    <a>内容管理<i class="layui-icon layui-right">&#xe619;</i></a>
                </li>
                <li class="layui-nav-item">
                    <a href="@Url.Action("List","Article")">文章管理</a>
                </li>
                <li class="layui-nav-item">
                    <a href="@Url.Action("List","Category")">分类管理</a>
                </li>
                <li class="layui-nav-item ">
                    <a href="javascript:;">留言管理</a>
                </li>
                <li class="layui-nav-item">
                    <a href="@Url.Action("List","Log")">操作日志</a>
                </li>
            </ul>
        </div>
        <div class="layui-body">
            @RenderBody()
        </div>
        <div class="layui-footer">
            <div class="layui-main">
                Beginner © www.zhengjinfan.com
            </div>
        </div>
    </div>
    <script src="~/Plugins/layui/layui.js"></script>
    <script src="~/Scripts/global.js"></script>
    @RenderSection("scripts", false)
</body>
</html>